steps:
  # ==================================================================
  # Step 0: Gradle 캐시 복원
  # ==================================================================
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'Restore Cache'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil cp gs://${_DEST_BUCKET}/cache/gradle_cache.tar.gz /tmp/cache.tar.gz || echo "No cache found"
        if [ -f /tmp/cache.tar.gz ]; then
          tar -xzf /tmp/cache.tar.gz -C /root/
          echo "✅ Cache restored."
        fi

  # ==================================================================
  # Step 1: config.json 동적 생성
  # ==================================================================
  - name: 'ubuntu'
    id: 'Create Config'
    script: |
      echo "Creating config.json from inputs..."
      
      cat <<EOF > app/config.json
      {
        "projectId": "${_PROJECT_ID}",
        "appName": "${_APP_NAME}",
        "packageName": "${_PACKAGE_NAME}",
        "loadingUrl": "${_LOADING_URL}",
        "appVersionName": "${_VERSION_NAME}",
        "appVersionCode": ${_VERSION_CODE}
      }
      EOF
      
      cat app/config.json

  # ==================================================================
  # Step 2: 앱 아이콘 다운로드
  # ==================================================================
  - name: 'gcr.io/cloud-builders/curl'
    id: 'Download Icon'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Downloading icon from ${_APP_ICON_URL}..."
        mkdir -p app/src/main/res/mipmap-xxxhdpi
        
        curl -L -o app/src/main/res/mipmap-xxxhdpi/ic_launcher.png "${_APP_ICON_URL}"
        cp app/src/main/res/mipmap-xxxhdpi/ic_launcher.png app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png

  # ==================================================================
  # Step 2-A: 앱 서명키 확인 및 다운로드
  # ==================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Check/Download Keystore'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # 변수명을 KEY_SECRET_ID로 변경하고 $$를 붙임
        KEY_SECRET_ID="keystore-${_PROJECT_ID}"
        echo "🔐 Checking Secret Manager for: $$KEY_SECRET_ID"
        
        if gcloud secrets versions access latest --secret="$$KEY_SECRET_ID" --out-file="app/keystore.jks"; then
          echo "✅ Keystore found and downloaded."
        else
          echo "⚠️ Keystore not found. Marking for creation."
          touch /tmp/create_new_keystore
        fi

  # ==================================================================
  # Step 2-B: 앱 서명키 생성 (없는 경우)
  # ==================================================================
  - name: 'asia-northeast3-docker.pkg.dev/appbox-479702/appbox-artifact-registry/android-builder:latest'
    id: 'Generate Keystore'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ -f /tmp/create_new_keystore ]; then
          echo "🆕 Generating new keystore..."
        
          # Bash 변수는 $$ 사용
          SALT="mobpa_secret_salt_v1"
          RAW_HASH=$(echo -n "${_PROJECT_ID}$$SALT" | sha256sum)
          ALIAS="key_$(echo -n $$RAW_HASH | cut -c1-10)"
          PASS="$(echo -n $$RAW_HASH | cut -c11-26)A1!"
        
          echo "Generated Alias: $$ALIAS"
        
          keytool -genkeypair -v \
            -keystore app/keystore.jks \
            -alias "$$ALIAS" \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass "$$PASS" \
            -keypass "$$PASS" \
            -dname "CN=${_APP_NAME}, OU=AppBox, O=MobPa, L=Seoul, C=KR"
        
          # 임시 저장
          echo "$$ALIAS" > /tmp/keystore_alias
          echo "$$PASS" > /tmp/keystore_pass
        
          echo "✅ New keystore generated."
        fi

  # ==================================================================
  # Step 2-C: 생성된 키 Secret Manager 업로드
  # ==================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Upload Keystore Secret'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ -f /tmp/create_new_keystore ]; then
          KEY_SECRET_ID="keystore-${_PROJECT_ID}"
          echo "📤 Uploading new keystore to Secret Manager..."
        
          # $$KEY_SECRET_ID 사용
          gcloud secrets create "$$KEY_SECRET_ID" --replication-policy="automatic" || true
          gcloud secrets versions add "$$KEY_SECRET_ID" --data-file="app/keystore.jks"
        
          echo "✅ Keystore saved to Secret Manager."
        fi

  # ==================================================================
  # Step 2-D: Gradle에 서명 정보 주입
  # ==================================================================
  - name: 'ubuntu'
    id: 'Inject Signing Config'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "💉 Injecting signing configuration..."
        GRADLE_FILE="app/build.gradle.kts"
        
        if [ -f /tmp/create_new_keystore ]; then
          ALIAS=$(cat /tmp/keystore_alias)
          PASS=$(cat /tmp/keystore_pass)
        else
          # 기존 키 복원 로직
          SALT="mobpa_secret_salt_v1"
          RAW_HASH=$(echo -n "${_PROJECT_ID}$$SALT" | sha256sum)
          ALIAS="key_$(echo -n $$RAW_HASH | cut -c1-10)"
          PASS="$(echo -n $$RAW_HASH | cut -c11-26)A1!"
        fi
        
        # $$ALIAS, $$PASS 사용
        sed -i "s|__KEYSTORE_PATH__|keystore.jks|g" $$GRADLE_FILE
        sed -i "s|__KEYSTORE_STORE_PASSWORD__|$$PASS|g" $$GRADLE_FILE
        sed -i "s|__KEY_ALIAS__|$$ALIAS|g" $$GRADLE_FILE
        sed -i "s|__KEY_PASSWORD__|$$PASS|g" $$GRADLE_FILE
        
        echo "✅ Signing config injected."

  # ==================================================================
  # Step 2-E: 프로젝트 소스 백업
  # ==================================================================
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'Archive Source'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "📦 Archiving project source..."
        tar -czf /tmp/source_backup.tar.gz --exclude=.git --exclude=.gradle --exclude=app/build .
        
        TARGET_PATH="${_OUTPUT_GCS_PATH%/}/${_VERSION_NAME}/source/"
        echo "📤 Uploading source to: $$TARGET_PATH"
        gsutil cp /tmp/source_backup.tar.gz "$$TARGET_PATH"

  # ==================================================================
  # Step 3: 안드로이드 빌드
  # ==================================================================
  - name: 'asia-northeast3-docker.pkg.dev/appbox-479702/appbox-artifact-registry/android-builder:latest'
    id: 'Build Artifacts'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        chmod +x gradlew
        ./gradlew assembleRelease bundleRelease --build-cache

  # ==================================================================
  # Step 4: Gradle 캐시 저장
  # ==================================================================
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'Save Cache'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "💾 Saving Gradle cache..."
        tar -czf /tmp/cache.tar.gz -C /root/ .gradle
        gsutil cp /tmp/cache.tar.gz gs://${_DEST_BUCKET}/cache/gradle_cache.tar.gz
        echo "✅ Cache saved."

  # ==================================================================
  # Step 5: 결과물 업로드
  # ==================================================================
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'Upload Artifacts'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🚀 Uploading artifacts..."
        
        BASE_PATH="${_OUTPUT_GCS_PATH%/}/${_VERSION_NAME}"
        APK_PATH="$$BASE_PATH/apk/"
        AAB_PATH="$$BASE_PATH/aab/"
        
        echo " - APK Path: $$APK_PATH"
        echo " - AAB Path: $$AAB_PATH"
        
        gsutil cp app/build/outputs/apk/release/*.apk "$$APK_PATH"
        gsutil cp app/build/outputs/bundle/release/*.aab "$$AAB_PATH"

# 변수 정의
substitutions:
  _PROJECT_ID: "AAA-000000"
  _APP_NAME: "앱박스"
  _PACKAGE_NAME: "kr.co.mobpa.sample.waveAppSuiteSdk"
  _LOADING_URL: "https://www.appboxapp.com/"
  _VERSION_NAME: "1.0.1"
  _VERSION_CODE: "1"
  _APP_ICON_URL: "https://via.placeholder.com/150"
  _OUTPUT_GCS_PATH: "gs://my-bucket/output/"
  _DEST_BUCKET: "my-bucket"

timeout: 3600s

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY