steps:
  # -----------------------------------------------------------------------------
  # Step 0: Gradle 캐시 복원
  # -----------------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'Restore Cache'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil cp gs://${_PRIVATE_BUCKET}/cache/gradle_cache.tar.gz /tmp/cache.tar.gz || echo "No cache found"
        if [ -f /tmp/cache.tar.gz ]; then
          tar -xzf /tmp/cache.tar.gz -C /root/
          echo "✅ Cache restored."
        fi

  # -----------------------------------------------------------------------------
  # Step 1: config.json 생성
  # -----------------------------------------------------------------------------
  - name: 'ubuntu'
    id: 'Create Config'
    env:
      - 'PROJECT_ID=${_PROJECT_ID}'
      - 'APP_NAME=${_APP_NAME}'
      - 'PACKAGE_NAME=${_PACKAGE_NAME}'
      - 'LOADING_URL=${_LOADING_URL}'
      - 'VERSION_NAME=${_VERSION_NAME}'
      - 'VERSION_CODE=${_VERSION_CODE}'
    script: |
      echo "🔍 Validating inputs..."
      
      if [ -z "$PROJECT_ID" ]; then echo "❌ Error: PROJECT_ID missing"; exit 1; fi
      
      cat <<EOF > app/config.json
      {
        "projectId": "$PROJECT_ID",
        "appName": "$APP_NAME",
        "packageName": "$PACKAGE_NAME",
        "loadingUrl": "$LOADING_URL",
        "appVersionName": "$VERSION_NAME",
        "appVersionCode": $VERSION_CODE
      }
      EOF
      
      if [ ! -s app/config.json ]; then echo "❌ Error: config failed"; exit 1; fi
      cat app/config.json

  # -----------------------------------------------------------------------------
  # Step 2: 앱 아이콘 다운로드 (포맷 자동 감지 및 확장자 자동 할당)
  # -----------------------------------------------------------------------------
  - name: 'ubuntu'
    id: 'Download Icon'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # 필수 패키지 설치 (curl, file)
        apt-get update && apt-get install -y curl file
        
        if [ -z "${_APP_ICON_URL}" ]; then echo "❌ Error: _APP_ICON_URL missing"; exit 1; fi
        
        # 디렉토리 생성 (절대 경로)
        ICON_DIR="/workspace/app/src/main/res/mipmap-xxxhdpi"
        mkdir -p "$$ICON_DIR"
        
        echo "⬇️ Downloading icon..."
        # 임시 파일로 다운로드
        if ! curl -L -o /tmp/temp_icon "${_APP_ICON_URL}"; then
           echo "❌ Error: Download failed"
           exit 1
        fi
        
        # 파일 타입 확인 (MIME Type 감지)
        FILE_TYPE=$(file --mime-type -b /tmp/temp_icon)
        echo "ℹ️ Detected file type: $$FILE_TYPE"
        
        # 타입에 따른 확장자 결정
        EXT="png" # 기본값
        if [[ "$$FILE_TYPE" == "image/jpeg" ]]; then EXT="jpg"; fi
        if [[ "$$FILE_TYPE" == "image/png" ]]; then EXT="png"; fi
        if [[ "$$FILE_TYPE" == "image/webp" ]]; then EXT="webp"; fi
        
        echo "ℹ️ Using extension: .$$EXT"
        
        # 기존 아이콘 파일 모두 삭제 (중복 방지)
        rm -f "$$ICON_DIR"/ic_launcher.*
        
        # 올바른 확장자로 복사
        cp /tmp/temp_icon "$$ICON_DIR/ic_launcher.$$EXT"
        cp /tmp/temp_icon "$$ICON_DIR/ic_launcher_round.$$EXT"
        
        # (선택) 만약 round 이미지가 별도로 필요하다면 여기서 처리
        
        echo "✅ Icon saved as ic_launcher.$$EXT"

  # -----------------------------------------------------------------------------
  # Step 3: 서명 키 확인
  # -----------------------------------------------------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Check/Download Keystore'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        KEY_SECRET_ID="keystore-${_PROJECT_ID}"
        echo "🔐 Checking: $$KEY_SECRET_ID"
        
        if gcloud secrets versions access latest --secret="$$KEY_SECRET_ID" --out-file="app/keystore.jks"; then
          echo "✅ Keystore found."
        else
          echo "⚠️ Keystore not found. Will create."
          touch create_new_keystore 
        fi

  # -----------------------------------------------------------------------------
  # Step 4: 서명 키 생성
  # -----------------------------------------------------------------------------
  - name: 'asia-northeast3-docker.pkg.dev/appbox-479702/appbox-artifact-registry/android-builder:latest'
    id: 'Generate Keystore'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ -f create_new_keystore ]; then
          echo "🆕 Generating keystore..."
          SALT="mobpa_secret_salt_v1"
          RAW_HASH=$(echo -n "${_PROJECT_ID}$$SALT" | sha256sum)
          ALIAS="key_$(echo -n $$RAW_HASH | cut -c1-10)"
          PASS="$(echo -n $$RAW_HASH | cut -c11-26)A1!"
        
          if ! keytool -genkeypair -v \
            -keystore app/keystore.jks \
            -alias "$$ALIAS" \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass "$$PASS" \
            -keypass "$$PASS" \
            -dname "CN=${_APP_NAME}, OU=AppBox, O=MobPa, L=Seoul, C=KR"; then
             echo "❌ Error: keytool failed"
             exit 1
          fi
        
          echo "$$ALIAS" > keystore_alias
          echo "$$PASS" > keystore_pass
          echo "✅ Keystore generated."
        fi

  # -----------------------------------------------------------------------------
  # Step 5: 서명 키 업로드
  # -----------------------------------------------------------------------------
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Upload Keystore Secret'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ -f create_new_keystore ]; then
          KEY_SECRET_ID="keystore-${_PROJECT_ID}"
          echo "📤 Uploading to Secret Manager..."
          gcloud secrets create "$$KEY_SECRET_ID" --replication-policy="automatic" || true
          if ! gcloud secrets versions add "$$KEY_SECRET_ID" --data-file="app/keystore.jks"; then
             echo "⚠️ Warning: Failed to upload key."
          else
             echo "✅ Keystore uploaded."
          fi
        fi

  # -----------------------------------------------------------------------------
  # Step 6: 사전 빌드 점검 (확장자 무관하게 확인)
  # -----------------------------------------------------------------------------
  - name: 'ubuntu'
    id: 'Pre-Build Check'
    script: |
      echo "🔍 Checking files in /workspace/app/..."
      
      if [ ! -s /workspace/app/config.json ]; then echo "❌ Error: app/config.json missing!"; exit 1; fi
      
      # [수정] 확장자가 jpg, png, webp 무엇이든 'ic_launcher'로 시작하는 파일이 있는지 확인
      ICON_COUNT=$(ls /workspace/app/src/main/res/mipmap-xxxhdpi/ic_launcher.* 2>/dev/null | wc -l)
      
      if [ "$ICON_COUNT" -eq "0" ]; then 
          echo "❌ Error: Icon missing at /workspace/app/src/main/res/mipmap-xxxhdpi/"
          exit 1; 
      fi
      
      if [ ! -s /workspace/app/keystore.jks ]; then echo "❌ Error: Keystore missing!"; exit 1; fi
      
      echo "✅ All files present."

  # -----------------------------------------------------------------------------
  # Step 7: Gradle 설정에 서명 정보 주입
  # -----------------------------------------------------------------------------
  - name: 'ubuntu'
    id: 'Inject Signing Config'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "💉 Injecting signing config..."
        GRADLE_FILE="app/build.gradle.kts"
        
        if [ ! -f "$$GRADLE_FILE" ]; then echo "❌ Error: $$GRADLE_FILE missing"; exit 1; fi

        if [ -f create_new_keystore ]; then
          ALIAS=$(cat keystore_alias)
          PASS=$(cat keystore_pass)
        else
          SALT="mobpa_secret_salt_v1"
          RAW_HASH=$(echo -n "${_PROJECT_ID}$$SALT" | sha256sum)
          ALIAS="key_$(echo -n $$RAW_HASH | cut -c1-10)"
          PASS="$(echo -n $$RAW_HASH | cut -c11-26)A1!"
        fi
        
        sed -i "s|__KEYSTORE_PATH__|keystore.jks|g" $$GRADLE_FILE
        sed -i "s|__KEYSTORE_STORE_PASSWORD__|$$PASS|g" $$GRADLE_FILE
        sed -i "s|__KEY_ALIAS__|$$ALIAS|g" $$GRADLE_FILE
        sed -i "s|__KEY_PASSWORD__|$$PASS|g" $$GRADLE_FILE
        
        echo "✅ Config injected."

  # -----------------------------------------------------------------------------
  # Step 8: 소스 백업
  # -----------------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'Archive Source'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "📦 Archiving source..."
        tar -czf /tmp/source_backup.tar.gz --exclude=.git --exclude=.gradle --exclude=app/build \
          --exclude=create_new_keystore --exclude=keystore_alias --exclude=keystore_pass .
        
        TARGET_PATH="gs://${_PRIVATE_BUCKET}/${_PROJECT_ID}/${_VERSION_NAME}/source/"
        echo "📤 Uploading to: $$TARGET_PATH"
        gsutil cp /tmp/source_backup.tar.gz "$$TARGET_PATH"

  # -----------------------------------------------------------------------------
  # Step 9: Android 빌드
  # -----------------------------------------------------------------------------
  - name: 'asia-northeast3-docker.pkg.dev/appbox-479702/appbox-artifact-registry/android-builder:latest'
    id: 'Build Artifacts'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        chmod +x gradlew
        ./gradlew assembleRelease bundleRelease --build-cache

  # -----------------------------------------------------------------------------
  # Step 10: 캐시 저장
  # -----------------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'Save Cache'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "💾 Saving cache..."
        tar -czf /tmp/cache.tar.gz -C /root/ .gradle
        gsutil cp /tmp/cache.tar.gz gs://${_PRIVATE_BUCKET}/cache/gradle_cache.tar.gz
        echo "✅ Cache saved."

  # -----------------------------------------------------------------------------
  # Step 11: 결과물 업로드
  # -----------------------------------------------------------------------------
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'Upload Artifacts'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "🚀 Uploading artifacts..."
        BASE_PATH="gs://${_PUBLIC_BUCKET}/${_PROJECT_ID}/${_VERSION_NAME}"
        APK_PATH="$$BASE_PATH/apk/"
        AAB_PATH="$$BASE_PATH/aab/"
        
        gsutil cp app/build/outputs/apk/release/*.apk "$$APK_PATH"
        gsutil cp app/build/outputs/bundle/release/*.aab "$$AAB_PATH"

substitutions:
  _PROJECT_ID: ""
  _APP_NAME: ""
  _PACKAGE_NAME: ""
  _LOADING_URL: ""
  _VERSION_NAME: "1.0.1"
  _VERSION_CODE: "1"
  _APP_ICON_URL: ""
  _PUBLIC_BUCKET: "appbox-public-assets"
  _PRIVATE_BUCKET: "appbox-build-artifacts"

timeout: 3600s

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY